spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bbs?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#    druid:
#      # 下面为连接池的补充设置，应用到上面所有数据源中
#      # 初始化大小，最小，最大
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      # 配置获取连接等待超时的时间
#      max-wait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      time-between-eviction-runs-millis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: true
#      test-on-return: false
#      # 打开PSCache，并且指定每个连接上PSCache的大小
#      pool-prepared-statements: true
#      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      max-pool-prepared-statement-per-connection-size: 20
#      filters: stat,wall
#      use-global-data-source-stat: true
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      # 配置监控服务器
#      stat-view-servlet:
#        # 1.1.10以后的版本需要指定为true 不然默认是关闭的就会出现404
#        enabled: true
#        login-username: admin
#        login-password: 123456
#        reset-enable: false
#        url-pattern: /druid/*
#      web-stat-filter:
#        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico

  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true

redis:
  host: localhost
  port: 6379
  timeout: 10
  poolMaxTotal: 1000
  poolMaxWait: 500
  poolMaxIdle: 500
